
services:
  mongodb-Backend-Avanzado:
    image: mongo:7
    container_name: mongo_local
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb-Backend-Avanzado:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: 'false'
    depends_on:
      - mongodb-Backend-Avanzado


volumes:
  mongo_data: